# Generated by Django 4.2.13 on 2024-07-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_player_flag', models.CharField(choices=[('Y', 'New Player'), ('N', 'Existing Player')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayedRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_score', models.IntegerField()),
                ('net_score', models.IntegerField()),
                ('net_rel_par', models.IntegerField()),
                ('coconut_pts', models.IntegerField(blank=True, null=True)),
                ('handicap_adjustment', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='golf_league.eventplayer')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_golf_course', models.CharField(blank=True, max_length=200, null=True)),
                ('event_status', models.CharField(choices=[('N', 'Not Started'), ('C', 'Completed'), ('R', 'Rainout')], default='N', max_length=1, null=True)),
                ('leagueseason', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='golf_league.leagueseason')),
            ],
        ),
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('effective_at', models.DateField()),
                ('update_user', models.CharField(blank=True, max_length=200, null=True)),
                ('update_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('golfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='golf_league.leagueplayer')),
                ('update_golf_round', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf_league.playedround')),
            ],
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='golfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='golf_league.leagueplayer'),
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='league_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='golf_league.leagueevent'),
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='played_round',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf_league.playedround'),
        ),
        migrations.AddField(
            model_name='eventplayer',
            name='round_handicap',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='golf_league.handicap'),
        ),
        migrations.AddConstraint(
            model_name='eventplayer',
            constraint=models.UniqueConstraint(fields=('golfer', 'league_event'), name='unique_player'),
        ),
    ]
